# Generated by Django 6.0.1 on 2026-01-09 13:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicoSuporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('assunto', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('aberto', 'Aberto'), ('atendimento', 'Em Atendimento'), ('aguardando', 'Aguardando Usuário'), ('fechado', 'Fechado')], default='aberto', max_length=20)),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta')], default='media', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chamados_suporte', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tópico de Suporte',
                'verbose_name_plural': 'Tópicos de Suporte',
                'ordering': ['-atualizado_em'],
            },
        ),
        migrations.CreateModel(
            name='MensagemSuporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.TextField()),
                ('arquivo_anexo', models.FileField(blank=True, null=True, upload_to='suporte/anexos/%Y/%m/%d/')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('remetente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('topico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='suporte.topicosuporte')),
            ],
            options={
                'verbose_name': 'Mensagem de Suporte',
                'verbose_name_plural': 'Mensagens de Suporte',
                'ordering': ['criado_em'],
            },
        ),
    ]
