# Generated by Django 6.0.1 on 2026-01-09 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suporte', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensagemsuporte',
            name='lida',
            field=models.BooleanField(default=False),
        ),
    ]
