# Generated by Django 6.0.1 on 2026-01-08 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='nome',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='sobrenome',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
