# Generated by Django 6.0.1 on 2026-01-09 15:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_profile_nome_profile_sobrenome'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('imagem_base', models.ImageField(upload_to='repositorio/categorias/')),
            ],
        ),
        migrations.CreateModel(
            name='Galeria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acesso_publico', models.BooleanField(default=False)),
                ('titulo', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('publicada', 'Publicada'), ('arquivada', 'Arquivada')], default='rascunho', max_length=20)),
                ('data_evento', models.DateField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='galerias', to='repositorio.categoria')),
                ('fotografo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galerias_criadas', to=settings.AUTH_USER_MODEL)),
                ('grupos_audiencia', models.ManyToManyField(blank=True, to='users.grupoaudiencia')),
            ],
            options={
                'ordering': ['-data_evento'],
            },
        ),
        migrations.CreateModel(
            name='MarcaDagua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('imagem', models.ImageField(upload_to='repositorio/watermarks/')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('fotografo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marcas_dagua', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Midia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo_original', models.FileField(upload_to='repositorio/originais/%Y/%m/%d/')),
                ('arquivo_processado', models.FileField(blank=True, null=True, upload_to='repositorio/processadas/%Y/%m/%d/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='repositorio/thumbs/%Y/%m/%d/')),
                ('status_processamento', models.CharField(choices=[('pendente', 'Pendente'), ('processando', 'Processando'), ('disponivel', 'Disponível'), ('erro', 'Erro')], default='pendente', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('galeria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='midias', to='repositorio.galeria')),
            ],
        ),
        migrations.AddField(
            model_name='galeria',
            name='capa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='galeria_capa', to='repositorio.midia'),
        ),
    ]
