# Generated by Django 6.0.1 on 2026-01-09 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositorio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='galeria',
            name='marca_dagua_padrao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='repositorio.marcadagua'),
        ),
        migrations.AlterField(
            model_name='midia',
            name='status_processamento',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('processando', 'Processando'), ('disponivel', 'Disponível'), ('erro', 'Erro')], db_index=True, default='pendente', max_length=20),
        ),
    ]
