# Generated by Django 6.0.1 on 2026-01-10 17:27

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositorio', '0002_galeria_marca_dagua_padrao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marcadagua',
            name='imagem',
            field=models.ImageField(storage=storages.backends.s3.S3Storage(), upload_to='repositorio/watermarks/'),
        ),
        migrations.AlterField(
            model_name='midia',
            name='arquivo_original',
            field=models.FileField(storage=storages.backends.s3.S3Storage(), upload_to='repositorio/originais/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='midia',
            name='arquivo_processado',
            field=models.FileField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to='repositorio/processadas/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='midia',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to='repositorio/thumbs/%Y/%m/%d/'),
        ),
    ]
