# Generated by Django 6.0.1 on 2026-01-10 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositorio', '0003_alter_marcadagua_imagem_alter_midia_arquivo_original_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marcadagua',
            name='opacidade',
            field=models.PositiveIntegerField(default=50),
        ),
    ]
