# Generated by Django 6.0.1 on 2026-01-11 18:28

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositorio', '0004_marcadagua_opacidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoHome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_imagem', models.ImageField(help_text='Imagem de destaque no topo da Home', storage=storages.backends.s3.S3Storage(), upload_to='repositorio/home/hero/')),
                ('hero_legenda', models.CharField(blank=True, help_text='Texto opcional para aparecer sobre a imagem', max_length=150)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração da Home',
                'verbose_name_plural': 'Configurações da Home',
            },
        ),
    ]
