# Generated by Django 6.0.1 on 2026-01-11 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositorio', '0005_configuracaohome'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configuracaohome',
            options={'verbose_name': 'Configuração da Home'},
        ),
        migrations.RemoveField(
            model_name='configuracaohome',
            name='atualizado_em',
        ),
        migrations.AddField(
            model_name='configuracaohome',
            name='hero_arte_sobreposta',
            field=models.ImageField(blank=True, help_text='Arte em PNG transparente para flutuar sobre o Hero', null=True, upload_to='home/arte/'),
        ),
        migrations.AlterField(
            model_name='configuracaohome',
            name='hero_imagem',
            field=models.ImageField(blank=True, null=True, upload_to='home/hero/'),
        ),
        migrations.AlterField(
            model_name='configuracaohome',
            name='hero_legenda',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
