# Generated by Django 6.0.1 on 2026-01-12 19:52

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositorio', '0006_alter_configuracaohome_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='imagem_base',
            field=models.ImageField(storage=storages.backends.s3.S3Storage(), upload_to='repositorio/categorias/'),
        ),
        migrations.AlterField(
            model_name='configuracaohome',
            name='hero_arte_sobreposta',
            field=models.ImageField(blank=True, help_text='Arte em PNG transparente para flutuar sobre o Hero', null=True, storage=storages.backends.s3.S3Storage(), upload_to='home/arte/'),
        ),
        migrations.AlterField(
            model_name='configuracaohome',
            name='hero_imagem',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to='home/hero/'),
        ),
    ]
