# Generated by Django 6.0.1 on 2026-01-12 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositorio', '0007_alter_categoria_imagem_base_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='imagem_base',
            field=models.ImageField(upload_to='categorias/'),
        ),
    ]
