# Generated by Django 6.0.1 on 2026-01-13 02:59

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositorio', '0008_alter_categoria_imagem_base'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracaohome',
            name='hero_arte_sobreposta',
            field=models.ImageField(blank=True, help_text='Arte em PNG transparente para flutuar sobre o Hero', null=True, storage=storages.backends.s3.S3Storage(), upload_to='acervo/home/arte/'),
        ),
        migrations.AlterField(
            model_name='configuracaohome',
            name='hero_imagem',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to='acervo/home/hero/'),
        ),
        migrations.AlterField(
            model_name='marcadagua',
            name='imagem',
            field=models.ImageField(storage=storages.backends.s3.S3Storage(), upload_to='acervo/watermarks/'),
        ),
        migrations.AlterField(
            model_name='midia',
            name='arquivo_original',
            field=models.FileField(storage=storages.backends.s3.S3Storage(), upload_to='acervo/originais/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='midia',
            name='arquivo_processado',
            field=models.FileField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to='acervo/processadas/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='midia',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to='acervo/thumbs/%Y/%m/%d/'),
        ),
    ]
