"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.1.
"""

import os
import environ
from pathlib import Path

# ==============================================================================
# 1. SETUP BÁSICO E VARIÁVEIS DE AMBIENTE
# ==============================================================================

BASE_DIR = Path(__file__).resolve().parent.parent

# Inicializa o django-environ
env = environ.Env(
    DEBUG=(bool, False)
)

# Lendo o arquivo .env
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

# Segurança
SECRET_KEY = env('SECRET_KEY')

# Modo DEBUG
DEBUG = env.bool('DEBUG')

ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=[])

# ==============================================================================
# 2. DEFINIÇÃO DE APLICATIVOS
# ==============================================================================

INSTALLED_APPS = [
    'daphne', # ASGI Server para WebSockets (deve ser o primeiro)
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_browser_reload',
    'tailwind',
    'theme',
    'channels', # Django Channels
    'core',
    'users',
    'historia',
    'contato',
    'perfil',
    'mensagens',
    'suporte',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_browser_reload.middleware.BrowserReloadMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'
ASGI_APPLICATION = 'config.asgi.application' # Configuração ASGI

# ==============================================================================
# 3. BANCO DE DADOS (Configurado via environ)
# ==============================================================================

DATABASES = {
    'default': env.db_url(
        'DATABASE_URL',
        default='sqlite:///' + str(BASE_DIR / 'db.sqlite3')
    )
}

# ==============================================================================
# 4. VALIDAÇÃO DE SENHA
# ==============================================================================

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',},
]

# ==============================================================================
# 5. INTERNACIONALIZAÇÃO (PT-BR)
# ==============================================================================

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True

# ==============================================================================
# 6. ARQUIVOS ESTÁTICOS E MÍDIA
# ==============================================================================

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    BASE_DIR / "static",           # Sua pasta static da raiz
    BASE_DIR / "theme" / "static",  # OBRIGATÓRIO: Onde o Tailwind salva o CSS
]

STATIC_ROOT = BASE_DIR / "staticfiles"

# ==============================================================================
# 7. CHAVE PRIMÁRIA PADRÃO
# ==============================================================================

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ==============================================================================
# 8. TAILWIND CSS
# ==============================================================================

TAILWIND_APP_NAME = 'theme'
INTERNAL_IPS = ['127.0.0.1']
TAILWIND_CSS_PATH = 'css/tailwind.css'
TAILWIND_BINARY_PATH = os.path.join(BASE_DIR, '.bin', 'tailwindcss.exe')


# ==============================================================================
# 9. CONFIGURAÇÕES DE AUTENTICAÇÃO E PERFIL
# ==============================================================================

# Define o modelo de usuário customizado
AUTH_USER_MODEL = 'users.User'

# URLs de redirecionamento
LOGIN_REDIRECT_URL = 'users:dashboard'
LOGOUT_REDIRECT_URL = 'users:login'
LOGIN_URL = 'users:login'

# ==============================================================================
# 10. CONFIGURAÇÃO DE E-MAIL (RECUPERAÇÃO DE SENHA)
# ==============================================================================

# Durante o desenvolvimento, as mensagens de e-mail serão exibidas no console
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# ==============================================================================
# 11. ARQUIVOS DE MÍDIA (UPLOAD DE FOTOS DE PERFIL)
# ==============================================================================

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# ==============================================================================
# 12. CHANNELS E REDIS
# ==============================================================================

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [('127.0.0.1', 6379)],
        },
    },
}